import type { OllamaServer, Model, ApiKey, HourlyStats, Alert, RequestLog } from './types'

export const SERVERS: OllamaServer[] = [
  {
    id: 'srv-01',
    name: 'gpu-server-01',
    url: 'http://192.168.1.10:11434',
    status: 'online',
    location: 'US-East / Rack A1',
    version: '0.5.4',
    gpus: [
      { id: 0, name: 'NVIDIA A100 80GB', vramTotalGiB: 80, vramUsedGiB: 43.2, tempC: 58, utilizationPct: 72, powerWatts: 280 },
      { id: 1, name: 'NVIDIA A100 80GB', vramTotalGiB: 80, vramUsedGiB: 28.4, tempC: 54, utilizationPct: 45, powerWatts: 210 },
    ],
    modelsLoaded: ['llama3.2', 'codestral', 'nomic-embed-text'],
    requestsPerMin: 28,
    responseTimeMs: 312,
    uptimePct: 99.98,
    addedAt: '2025-11-15T08:00:00Z',
    lastSeen: '2026-06-27T10:22:45Z',
    totalRequests: 45231,
  },
  {
    id: 'srv-02',
    name: 'gpu-server-02',
    url: 'http://192.168.1.11:11434',
    status: 'online',
    location: 'US-East / Rack A2',
    version: '0.5.4',
    gpus: [
      { id: 0, name: 'NVIDIA RTX 4090', vramTotalGiB: 24, vramUsedGiB: 18.6, tempC: 72, utilizationPct: 85, powerWatts: 380 },
    ],
    modelsLoaded: ['llama3.2', 'mistral'],
    requestsPerMin: 15,
    responseTimeMs: 285,
    uptimePct: 99.85,
    addedAt: '2025-12-01T09:30:00Z',
    lastSeen: '2026-06-27T10:22:50Z',
    totalRequests: 22470,
  },
  {
    id: 'srv-03',
    name: 'gpu-server-03',
    url: 'http://192.168.1.12:11434',
    status: 'degraded',
    location: 'US-East / Rack B3',
    version: '0.5.1',
    gpus: [
      { id: 0, name: 'NVIDIA RTX 3090', vramTotalGiB: 24, vramUsedGiB: 22.1, tempC: 87, utilizationPct: 95, powerWatts: 340 },
    ],
    modelsLoaded: ['llava'],
    requestsPerMin: 4,
    responseTimeMs: 1240,
    uptimePct: 97.2,
    addedAt: '2026-01-10T11:00:00Z',
    lastSeen: '2026-06-27T10:22:10Z',
    totalRequests: 1205,
  },
]

export const MODELS: Model[] = [
  {
    id: 'llama3.2',
    name: 'llama3.2',
    displayName: 'Llama 3.2',
    family: 'Llama',
    sizeGiB: 4.7,
    parametersBillion: 3,
    quantization: 'Q4_K_M',
    contextLength: 128000,
    category: 'general',
    servers: ['srv-01', 'srv-02'],
    totalRequests: 45231,
    avgLatencyMs: 312,
    tokensPerSec: 42.3,
    lastUsed: '2 min ago',
  },
  {
    id: 'codestral',
    name: 'codestral',
    displayName: 'Codestral 22B',
    family: 'Mistral',
    sizeGiB: 12.9,
    parametersBillion: 22,
    quantization: 'Q4_K_M',
    contextLength: 32768,
    category: 'code',
    servers: ['srv-01'],
    totalRequests: 12450,
    avgLatencyMs: 890,
    tokensPerSec: 18.7,
    lastUsed: '5 min ago',
  },
  {
    id: 'mistral',
    name: 'mistral',
    displayName: 'Mistral 7B',
    family: 'Mistral',
    sizeGiB: 4.1,
    parametersBillion: 7,
    quantization: 'Q4_0',
    contextLength: 32768,
    category: 'general',
    servers: ['srv-02'],
    totalRequests: 8320,
    avgLatencyMs: 285,
    tokensPerSec: 48.2,
    lastUsed: '8 min ago',
  },
  {
    id: 'llava',
    name: 'llava',
    displayName: 'LLaVA 7B',
    family: 'LLaVA',
    sizeGiB: 4.7,
    parametersBillion: 7,
    quantization: 'Q4_0',
    contextLength: 4096,
    category: 'vision',
    servers: ['srv-03'],
    totalRequests: 1205,
    avgLatencyMs: 1240,
    tokensPerSec: 12.4,
    lastUsed: '45 min ago',
  },
  {
    id: 'nomic-embed-text',
    name: 'nomic-embed-text',
    displayName: 'Nomic Embed Text',
    family: 'Nomic',
    sizeGiB: 0.27,
    parametersBillion: 0.137,
    quantization: 'F16',
    contextLength: 8192,
    category: 'embedding',
    servers: ['srv-01'],
    totalRequests: 23100,
    avgLatencyMs: 45,
    tokensPerSec: 820,
    lastUsed: '1 min ago',
  },
]

export const API_KEYS: ApiKey[] = [
  {
    id: 'key-01',
    name: 'production-app',
    keyMasked: 'sk-vyn-prod-a4f8...3k2p',
    createdAt: '2025-11-20',
    lastUsed: '1 min ago',
    requestsToday: 2430,
    requestsTotal: 89240,
    rateLimitRpm: 100,
    rateLimitTpm: 50000,
    status: 'active',
    allowedModels: null,
    createdBy: 'admin',
  },
  {
    id: 'key-02',
    name: 'dev-team',
    keyMasked: 'sk-vyn-dev-b7c2...9m5x',
    createdAt: '2025-12-05',
    lastUsed: '8 min ago',
    requestsToday: 456,
    requestsTotal: 12340,
    rateLimitRpm: 30,
    rateLimitTpm: null,
    status: 'active',
    allowedModels: ['llama3.2', 'codestral', 'mistral'],
    createdBy: 'admin',
  },
  {
    id: 'key-03',
    name: 'ci-pipeline',
    keyMasked: 'sk-vyn-ci-e3a1...7n8w',
    createdAt: '2026-01-12',
    lastUsed: '58 min ago',
    requestsToday: 123,
    requestsTotal: 4580,
    rateLimitRpm: 20,
    rateLimitTpm: null,
    status: 'active',
    allowedModels: ['codestral', 'nomic-embed-text'],
    createdBy: 'admin',
  },
  {
    id: 'key-04',
    name: 'old-staging',
    keyMasked: 'sk-vyn-stg-f9d4...1p6r',
    createdAt: '2025-10-18',
    lastUsed: '32 days ago',
    requestsToday: 0,
    requestsTotal: 3210,
    rateLimitRpm: 50,
    rateLimitTpm: null,
    status: 'revoked',
    allowedModels: null,
    createdBy: 'admin',
  },
]

// 24-hour hourly stats (index 0 = midnight)
const BASE_HOURLY = [35, 22, 18, 15, 20, 48, 142, 320, 580, 820, 980, 1050, 1120, 1080, 1010, 960, 920, 830, 720, 580, 420, 295, 190, 95]

export const HOURLY_STATS: HourlyStats[] = BASE_HOURLY.map((req, i) => ({
  hour: `${i.toString().padStart(2, '0')}:00`,
  requests: req,
  tokensIn: req * 185,
  tokensOut: req * 430,
  avgLatencyMs: 185 + Math.round(Math.sin(i / 3) * 40),
  p95LatencyMs: 620 + Math.round(Math.sin(i / 3) * 120),
  errors: Math.round(req * 0.008),
}))

export const ALERTS: Alert[] = [
  {
    id: 'alert-01',
    type: 'gpu_temp',
    severity: 'critical',
    message: 'GPU temperature 87°C exceeds threshold (85°C)',
    serverId: 'srv-03',
    serverName: 'gpu-server-03',
    timestamp: '12 min ago',
    resolved: false,
  },
  {
    id: 'alert-02',
    type: 'vram',
    severity: 'warning',
    message: 'VRAM utilisation 92% on RTX 3090',
    serverId: 'srv-03',
    serverName: 'gpu-server-03',
    timestamp: '12 min ago',
    resolved: false,
  },
  {
    id: 'alert-03',
    type: 'vram',
    severity: 'warning',
    message: 'RTX 4090 utilisation >80% sustained for 30 min',
    serverId: 'srv-02',
    serverName: 'gpu-server-02',
    timestamp: '45 min ago',
    resolved: false,
  },
  {
    id: 'alert-04',
    type: 'gpu_temp',
    severity: 'warning',
    message: 'A100[1] temperature spike to 82°C — resolved',
    serverId: 'srv-01',
    serverName: 'gpu-server-01',
    timestamp: '2 hr ago',
    resolved: true,
  },
]

export const RECENT_REQUESTS: RequestLog[] = [
  { id: 'r01', timestamp: '2s ago', model: 'llama3.2', serverId: 'srv-01', serverName: 'gpu-server-01', apiKeyName: 'production-app', tokensIn: 245, tokensOut: 612, latencyMs: 312, status: 'success' },
  { id: 'r02', timestamp: '4s ago', model: 'nomic-embed-text', serverId: 'srv-01', serverName: 'gpu-server-01', apiKeyName: 'production-app', tokensIn: 180, tokensOut: 768, latencyMs: 45, status: 'success' },
  { id: 'r03', timestamp: '8s ago', model: 'codestral', serverId: 'srv-01', serverName: 'gpu-server-01', apiKeyName: 'dev-team', tokensIn: 892, tokensOut: 1204, latencyMs: 890, status: 'success' },
  { id: 'r04', timestamp: '12s ago', model: 'mistral', serverId: 'srv-02', serverName: 'gpu-server-02', apiKeyName: 'production-app', tokensIn: 312, tokensOut: 487, latencyMs: 285, status: 'success' },
  { id: 'r05', timestamp: '18s ago', model: 'llama3.2', serverId: 'srv-02', serverName: 'gpu-server-02', apiKeyName: 'dev-team', tokensIn: 180, tokensOut: 842, latencyMs: 298, status: 'success' },
  { id: 'r06', timestamp: '25s ago', model: 'llava', serverId: 'srv-03', serverName: 'gpu-server-03', apiKeyName: 'dev-team', tokensIn: 2048, tokensOut: 312, latencyMs: 1240, status: 'error' },
  { id: 'r07', timestamp: '34s ago', model: 'nomic-embed-text', serverId: 'srv-01', serverName: 'gpu-server-01', apiKeyName: 'ci-pipeline', tokensIn: 150, tokensOut: 768, latencyMs: 42, status: 'success' },
  { id: 'r08', timestamp: '45s ago', model: 'llama3.2', serverId: 'srv-01', serverName: 'gpu-server-01', apiKeyName: 'production-app', tokensIn: 405, tokensOut: 780, latencyMs: 325, status: 'success' },
  { id: 'r09', timestamp: '58s ago', model: 'codestral', serverId: 'srv-01', serverName: 'gpu-server-01', apiKeyName: 'production-app', tokensIn: 720, tokensOut: 1540, latencyMs: 945, status: 'success' },
  { id: 'r10', timestamp: '1m ago', model: 'mistral', serverId: 'srv-02', serverName: 'gpu-server-02', apiKeyName: 'ci-pipeline', tokensIn: 220, tokensOut: 390, latencyMs: 280, status: 'success' },
]

// Summary stats
export const SUMMARY = {
  serversTotal: 3,
  serversOnline: 2,
  serversDegraded: 1,
  serversOffline: 0,
  modelsLoaded: 6, // instances (llama3.2 × 2 servers)
  modelsUnique: 5,
  requestsPerMin: 47,
  tokensToday: 5_423_850,
  requestsToday: BASE_HOURLY.slice(0, 11).reduce((a, b) => a + b, 0), // up to current hour
  errorsToday: 42,
  gatewayLatencyP50: 312,
  gatewayLatencyP95: 890,
  activeKeys: 3,
}
